name = "image-background-remover"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "imagebackgroundremover.club/*", zone_name = "imagebackgroundremover.club" },
  { pattern = "www.imagebackgroundremover.club/*", zone_name = "imagebackgroundremover.club" }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "image-background-remover-db"
database_id = "79edcff9-3be2-47e9-8a29-d26eb7eac838"

[vars]
MAX_FILE_SIZE_MB = "10"
GOOGLE_CLIENT_ID = "884413046007-o07vvihre5ro5l0g4fpmn5vfq0tt7s8s.apps.googleusercontent.com"
AUTH_GOOGLE_ID = "884413046007-o07vvihre5ro5l0g4fpmn5vfq0tt7s8s.apps.googleusercontent.com"
AUTH_URL = "https://imagebackgroundremover.club"
NEXTAUTH_URL = "https://imagebackgroundremover.club"
